<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Enterprise Edition</strong> Trial Period' => '',
    '<strong>Invalid</strong> Enterprise Edition Licence' => '',
    '<strong>Register</strong> Enterprise Edition' => '',
    '<strong>Unregistered</strong> Enterprise Edition' => '',
    'Enterprise Edition' => '',
    'Please enter your <strong>HumHub - Enterprise Edition</strong> licence key below. If you don\'t have a licence key yet, you can obtain one at %link%.' => '',
    'Please register this <strong>HumHub - Enterprise Edition</strong>!' => '',
    'Please update this <strong>HumHub - Enterprise Edition</strong> licence!' => '',
    'Registration successful!' => '',
    'Validating...' => '',
    'You have <strong>{daysLeft}</strong> days left in your trial period.' => '',
];
