<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<i class="fa fa-plus"></i> %itemTitle%' => '<i class="fa fa-plus"></i> %itemTitle%',
    '<strong>Change</strong> type' => '<strong>Ändere</strong> den Spacetyp',
    '<strong>Create</strong> new %typeTitle%' => '<strong>%typeTitle%</strong> erstellen',
    '<strong>Create</strong> new space type' => '<strong>Erstelle</strong> einen neuen Spacetyp',
    '<strong>Delete</strong> space type' => 'Spacetyp <strong>löschen</strong>',
    '<strong>Edit</strong> space type' => 'Spacetyp <strong>bearbeiten</strong>',
    'Create new type' => 'Erstelle einen neuen Spacetyp',
    'To delete the space type <strong>"{type}"</strong> you need to set an alternative type for existing spaces:' => 'Um den Spacetyp <strong>"{type}"</strong> löschen zu können, musst du für vorhandene Spaces einen anden Spacetyp auswählen:',
    'Type' => 'Spacetyp',
    'Types' => 'Spacetypen',
    'e.g. Project' => 'z.B. Projekt',
    'e.g. Projects' => 'z.B. Projekte',
];
