<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'e.g. Project' => '',
    'e.g. Projects' => '',
    '<i class="fa fa-plus"></i> %itemTitle%' => '<i class="fa fa-plus"></i> %itemTitle%',
    '<strong>Change</strong> type' => '<strong>Skift</strong> type',
    '<strong>Create</strong> new %typeTitle%' => '<strong>Opret</strong> ny %typeTitle%',
    '<strong>Create</strong> new space type' => '<strong>Opret</strong> ny side type',
    '<strong>Delete</strong> space type' => '<strong>Slet</strong> side type',
    '<strong>Edit</strong> space type' => '<strong>Rediger</strong> side type',
    'Create new type' => 'Opret ny type',
    'To delete the space type <strong>"{type}"</strong> you need to set an alternative type for existing spaces:' => 'For at slette side typen <strong>"{type}"</strong> så er du nødt til at angive en alternativ type for eksisterende side.',
    'Type' => 'Type',
    'Types' => 'Typer',
];
