<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<i class="fa fa-plus"></i> %itemTitle%' => '<i class="fa fa-plus"></i> %itemTitle%',
    '<strong>Change</strong> type' => '<strong>Modifier</strong> le type',
    '<strong>Create</strong> new %typeTitle%' => '<strong>Créer</strong> un nouveau %typeTitle%',
    '<strong>Create</strong> new space type' => '<strong>Créer</strong> un nouveau type d\'espace',
    '<strong>Delete</strong> space type' => '<strong>Supprimer</strong> le type d\'espace',
    '<strong>Edit</strong> space type' => '<strong>Modifier</strong> le type d\'espace',
    'Create new type' => 'Créer un nouveau type',
    'To delete the space type <strong>"{type}"</strong> you need to set an alternative type for existing spaces:' => 'Pour supprimer le type d\'espace <strong>"{type}"</strong>, vous devez définir un type alternatif pour les espaces existants :',
    'Type' => 'Type',
    'Types' => 'Types',
    'e.g. Project' => 'par ex. Projet',
    'e.g. Projects' => 'par ex. Projets',
];
