<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'At the end of your process you will be able to select potential partner candidates' => '',
    'Start' => '',
    'Enjoy!' => '',
    'Welcome to NIR-VANA, you have joined a room where you will interact with your innovator advisor.' => '',
    'On the top of your main pages you will see the general progress of the advice process:.' => '',
    'Wellcome to NIR-VANA, you have joined a room where you will interact with your innovator advisor.' => '',
    'You can click on any step to see the actions being involved. The green colour will show you your progress.' => '',
    'You will be guided through the advice process through some cards that will show you witch actions' => '',
    'and start a private and IP Protected discussion space with them. You will then decide wether your advisor will or will not' => '',
    'have access to this space.' => '',
    'need to be done. Some will be mandatory and have a deadline, while some others will be dismissible.' => '',
];
