<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<i class="fa fa-plus"></i> %itemTitle%' => '<i class="fa fa-plus"></i> %itemTitle%',
    '<strong>Change</strong> type' => '<strong>Zmień</strong> typ',
    '<strong>Create</strong> new %typeTitle%' => '<strong>Utwórz</strong> nowy %typeTitle%',
    '<strong>Create</strong> new space type' => '<strong>Utwórz</strong> nowy typ strefy',
    '<strong>Delete</strong> space type' => '<strong>Usuń</strong> ten typ strefy',
    '<strong>Edit</strong> space type' => '<strong>Edytuj</strong> ten typ strefy',
    'Create new type' => 'Utwórz nowy typ',
    'To delete the space type <strong>"{type}"</strong> you need to set an alternative type for existing spaces:' => 'Aby usunąć typ strefy <strong>"{type}"</strong> musisz ustawić alternatywny typ dla istniejących stref:',
    'Type' => 'Typ',
    'Types' => 'Typy',
    'e.g. Project' => 'np. Projekt',
    'e.g. Projects' => 'np. Projekty',
];
