<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<i class="fa fa-plus"></i> %itemTitle%' => '<i class="fa fa-plus"></i> %itemTitle%',
    '<strong>Change</strong> type' => '<strong>Verander</strong> type',
    '<strong>Create</strong> new %typeTitle%' => '<strong>Maak</strong> een nieuwe %typeTitle% Space',
    '<strong>Create</strong> new space type' => '<strong>Maak</strong> nieuw space type',
    '<strong>Delete</strong> space type' => '<strong>Verwijder</strong> space type',
    '<strong>Edit</strong> space type' => '<strong>bewerk</strong> space type',
    'Create new type' => 'Nieuw type maken',
    'To delete the space type <strong>"{type}"</strong> you need to set an alternative type for existing spaces:' => 'Om het space type <strong>"{type}"</strong>te verwijderen, moet je een alternatief instellen voor Spaces in dit type:',
    'Type' => 'Type',
    'Types' => 'Types',
    'e.g. Project' => 'bijvoorbeeld Project',
    'e.g. Projects' => 'bijvoorbeeld Projecten',
];
