<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Save' => '',
    'Saved' => '',
    'The email whitelist allows you to specify email rules for restricting allowed email adresses for user registration and invites.' => '',
    'The email whitelist allows you to specify email rules for users who don\'t need to be approved after registration.' => '',
    'The follwing emails do not match the whitelist settings: {emails}' => '',
    'The given email address is not allowed for registration!' => '',
    'Whitelist' => '',
];
